const N=8,boardEl=document.querySelector('#board'),piecesEl=document.querySelector('#pieces'),scoreEl=document.querySelector('#score'),msg=document.querySelector('#message');let board,hand,selected,score;
const SHAPES=[[[0,0]],[[0,0],[0,1]],[[0,0],[1,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[1,0],[1,1]],[[0,0],[1,0],[1,1]],[[0,1],[1,0],[1,1]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[1,1],[2,1]]];
function randomShape(){return SHAPES[Math.floor(Math.random()*SHAPES.length)];}
function newHand(){hand=[randomShape(),randomShape(),randomShape()];selected=null;renderPieces();}
function canPlace(shape,r,c){return shape.every(([dr,dc])=>r+dr<N&&c+dc<N&&!board[r+dr][c+dc]);}
function anyMove(){return hand.some(s=>s&&board.some((_,r)=>board[r].some((__,c)=>canPlace(s,r,c))));}
function clearLines(){let rows=[],cols=[];for(let r=0;r<N;r++)if(board[r].every(Boolean))rows.push(r);for(let c=0;c<N;c++)if(board.every(row=>row[c]))cols.push(c);rows.forEach(r=>board[r].fill(0));cols.forEach(c=>board.forEach(row=>row[c]=0));let n=rows.length+cols.length;if(n){score+=n*80;msg.textContent=n+' garis bersih!';}}
function place(r,c){if(selected===null||!hand[selected])return;let s=hand[selected];if(!canPlace(s,r,c)){msg.textContent='Bentuk tidak muat di posisi itu.';return;}s.forEach(([dr,dc])=>board[r+dr][c+dc]=1);score+=s.length*10;hand[selected]=null;selected=null;clearLines();if(hand.every(x=>!x))newHand();render();if(!anyMove()){msg.textContent='Game over — tidak ada langkah lagi.';}}
function render(){boardEl.innerHTML='';for(let r=0;r<N;r++)for(let c=0;c<N;c++){let b=document.createElement('button');b.className='cell'+(board[r][c]?' on':'');b.onclick=()=>place(r,c);boardEl.appendChild(b)}scoreEl.textContent=score;renderPieces();}
function renderPieces(){piecesEl.innerHTML='';hand.forEach((s,i)=>{let wrap=document.createElement('button');wrap.className='piece'+(selected===i?' selected':'');if(!s){wrap.style.visibility='hidden';piecesEl.appendChild(wrap);return;}let mr=Math.max(...s.map(x=>x[0]))+1,mc=Math.max(...s.map(x=>x[1]))+1,mini=document.createElement('div');mini.className='mini';mini.style.gridTemplateColumns=`repeat(${mc},17px)`;for(let r=0;r<mr;r++)for(let c=0;c<mc;c++){let d=document.createElement('span');d.className='dot'+(s.some(x=>x[0]===r&&x[1]===c)?'':' off');mini.appendChild(d)}wrap.appendChild(mini);wrap.onclick=()=>{selected=i;msg.textContent='Sekarang tap posisi di papan.';renderPieces()};piecesEl.appendChild(wrap)});}
function start(){board=Array.from({length:N},()=>Array(N).fill(0));score=0;msg.textContent='Pilih bentuk, lalu tap posisi di papan.';newHand();render();}document.querySelector('#restart').onclick=start;start();